config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Shows all of the pages
  # Read
  def index
    @pages = Page.all 
    # Render index.hitml.erb
  end

  # Show a single page
  # Read
  def show
    @page = Page.find(params[:id])
    # Render show.html.erb
  end

  # Shows the create form
  # New page in memory 
  def new
    @page = Page.new
    # Render new.html.erb
  end

  # POST
  # Try add on to the database
  def create 
    @page = Page.new(pages_params)

    if @page.save
      redirect_to pages_path
    else
      render :new 
    end
  end

  # Show the edit form
  def edit
    @page = Page.find(params[:id])
    # Render edit.html.erb
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(pages_params)
      redirect_to pages_path
    else
      render :edit 
    end
  end

  def destroy 
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  # CRUD 
  # Create
  # Read
  # Update
  # Destroy

  private

    def pages_params
      # attr_accessors 
      # { page: {title: 'new' ...}}
      params.require(:page).permit(:title, :author, :body)
      # { title: 'new' ...}
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # Render index.html.erb
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'home', root_path %>
<%= link_to "about", about_path %>
<%= link_to 'pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :auhor %>
  <%= f.text_field :auhor %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/pages/index.html.erb
<h1>All Pages</h1>
<% @pages.each do |page| %>
  <%= page.title %>
  <%= link_to 'Show Page', page_path(page) %>
  <%= link_to 'Edit Page', edit_page_path(page) %>
  <%= link_to 'Delete Page', page, method: :delete %>
<% end %>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<%= form_for @page do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :auhor %>
  <%= f.text_field :auhor %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <% end %>

app/views/pages/show.html.erb
<%= @page.title %>

<%= @page.author %>
<%= @page.body %>

<%= link_to 'Back', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>